# Generated by Django 5.2.5 on 2025-08-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mercadopago', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaomercadopago',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_mp', to='produtos.pedido', verbose_name='Pedido Original'),
        ),
    ]
