# Generated by Django 5.2.4 on 2025-07-30 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Banner')),
                ('imagem', models.ImageField(upload_to='banners/', verbose_name='Imagem do Banner')),
                ('url_destino', models.URLField(blank=True, null=True, verbose_name='URL de Destino')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável (gerado automaticamente ou manual)', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Categoria')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa no Site')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ (somente números)')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='Email de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendedores/logos/', verbose_name='Logo do Vendedor')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço Completo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no Site')),
                ('status_aprovacao', models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('aprovado', 'Aprovado'), ('suspenso', 'Suspenso'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10, verbose_name='Status de Aprovação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['nome_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_oferta', models.CharField(choices=[('unidade', 'Venda por Unidade (Imediata)'), ('lote', 'Compra Coletiva por Lote')], default='unidade', max_length=10, verbose_name='Tipo de Oferta')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Oferta')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável da oferta', max_length=255, unique=True)),
                ('descricao_detalhada', models.TextField(verbose_name='Descrição Detalhada da Oferta')),
                ('destaque', models.BooleanField(default=False, verbose_name='Oferta em Destaque')),
                ('preco_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Original')),
                ('preco_desconto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço com Desconto')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início da Oferta')),
                ('data_termino', models.DateTimeField(verbose_name='Data de Término da Oferta')),
                ('quantidade_minima_ativacao', models.IntegerField(default=1, verbose_name='Quantidade Mínima de Cupons para Ativação')),
                ('quantidade_maxima_cupons', models.IntegerField(blank=True, null=True, verbose_name='Quantidade Máxima de Cupons (Limite)')),
                ('quantidade_vendida', models.IntegerField(default=0, verbose_name='Quantidade de Cupons Vendidos')),
                ('imagem_principal', models.ImageField(upload_to='ofertas/imagens/', verbose_name='Imagem Principal da Oferta')),
                ('publicada', models.BooleanField(default=False, verbose_name='Publicada (Visível no Site)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ativa', 'Ativa'), ('sucesso', 'Sucesso (mínimo atingido)'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada'), ('falha_lote', 'Falha (mínimo não atingido)')], default='pendente', max_length=20, verbose_name='Status da Oferta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='ofertas.categoria', verbose_name='Categoria')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='ofertas.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Nota (1-5)')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_avaliacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Avaliador')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='ofertas.oferta', verbose_name='Oferta Avaliada')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_avaliacao'],
                'unique_together': {('oferta', 'usuario')},
            },
        ),
    ]
