# Generated by Django 5.2.4 on 2025-07-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='ofertas/imagens/', verbose_name='Imagem Principal da Oferta'),
        ),
    ]
