# Generated by Django 5.2.4 on 2025-07-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='oferta',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AddField(
            model_name='oferta',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Oferta em Destaque'),
        ),
    ]
