# Generated by Django 5.2.4 on 2025-07-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='tipo_oferta',
            field=models.CharField(choices=[('unidade', 'Venda por Unidade (Imediata)'), ('lote', 'Compra Coletiva por Lote')], default='unidade', max_length=10, verbose_name='Tipo de Oferta'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável (gerado automaticamente ou manual)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável da oferta', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ativa', 'Ativa'), ('sucesso', 'Sucesso (mínimo atingido)'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada'), ('falha_lote', 'Falha (mínimo não atingido)')], default='pendente', max_length=20, verbose_name='Status da Oferta'),
        ),
    ]
