# Generated by Django 5.2.2 on 2025-08-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, unique=True, verbose_name='ID do Pagamento no Mercado Pago')),
                ('status', models.CharField(default='pendente', max_length=50, verbose_name='Status do Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Transação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('meio_pagamento_tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Meio de Pagamento')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Cliente')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
            ],
        ),
    ]
