# Generated by Django 5.2.2 on 2025-08-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_product_id', models.CharField(max_length=255, verbose_name='ID Produto Stripe')),
                ('produto_id_original', models.IntegerField(blank=True, null=True, verbose_name='ID do Produto Original (Django)')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Item')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal do Item')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID da Sessão Stripe')),
                ('mercadopago_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID do Pagamento Mercado Pago')),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('mercadopago', 'Mercado Pago')], max_length=20, null=True, verbose_name='Método de Pagamento')),
                ('email_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email do Cliente')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20, verbose_name='Status do Pedido')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('categoria_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Categoria (URL-friendly)')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL Amigável)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('stock', models.IntegerField(default=0, verbose_name='Estoque')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU (Código do Produto)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('dimensoes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensões (AxLxP)')),
                ('garantia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Garantia')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produtos/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Alternativo')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagem Principal')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'ordering': ['-is_main', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegiaoFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo_cep', models.CharField(max_length=3, unique=True, verbose_name='Prefixo do CEP')),
                ('cidade', models.CharField(max_length=100)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prazo_entrega', models.PositiveIntegerField(verbose_name='Prazo (dias úteis)')),
            ],
        ),
    ]
