# Generated by Django 5.2.2 on 2025-09-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoimage',
            name='embedding',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Vetor de Embedding (IA)'),
        ),
    ]
