# Generated by Django 5.2.2 on 2025-10-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produtoimage_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoimage',
            name='embedding',
        ),
        migrations.AddField(
            model_name='produto',
            name='revisado',
            field=models.BooleanField(default=False, verbose_name='Revisado por Humano'),
        ),
    ]
