# Generated by Django 5.2.4 on 2025-07-30 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('data_compra', models.DateTimeField(auto_now_add=True, verbose_name='Data da Compra')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada'), ('aguardando_lote', 'Aguardando Concretização do Lote'), ('lote_cancelado', 'Lote Cancelado (Reembolsado)'), ('lote_cancelado_com_credito', 'Lote Cancelado (Crédito Gerado)')], default='pendente', max_length=50, verbose_name='Status do Pagamento')),
                ('id_transacao_mp', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Transação MP')),
                ('id_preferencia_mp', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Preferência MP')),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pagamento')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='ofertas.oferta', verbose_name='Oferta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código do Cupom')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('resgatado', 'Resgatado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='disponivel', max_length=10, verbose_name='Status do Cupom')),
                ('valido_ate', models.DateTimeField(verbose_name='Válido Até')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_resgate', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resgate')),
                ('compra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupom_unidade', to='compras.compra', verbose_name='Compra por Unidade')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to='ofertas.oferta', verbose_name='Oferta')),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
