# Generated by Django 5.2.4 on 2025-07-28 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade de Cupons Comprados')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total da Compra')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('reembolsada', 'Reembolsada')], default='pendente', max_length=20, verbose_name='Status do Pagamento')),
                ('id_transacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Transação (Gateway de Pagamento)')),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pagamento')),
                ('data_compra', models.DateTimeField(auto_now_add=True, verbose_name='Data da Compra')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='ofertas.oferta', verbose_name='Oferta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='Código do Cupom')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('resgatado', 'Resgatado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='disponivel', max_length=20, verbose_name='Status do Cupom')),
                ('data_resgate', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resgate')),
                ('valido_ate', models.DateTimeField(verbose_name='Válido Até')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to='compras.compra', verbose_name='Compra Relacionada')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons_gerados', to='ofertas.oferta', verbose_name='Oferta')),
                ('resgatado_por_vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ofertas.vendedor', verbose_name='Resgatado Pelo Vendedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_cupons', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Dono do Cupom')),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
            },
        ),
    ]
