# Generated by Django 5.2.4 on 2025-07-28 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('ofertas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupom',
            options={'ordering': ['-data_geracao'], 'verbose_name': 'Cupom', 'verbose_name_plural': 'Cupons'},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='cupom',
            name='resgatado_por_vendedor',
        ),
        migrations.AddField(
            model_name='cupom',
            name='resgatado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupons_resgatados_por_mim', to=settings.AUTH_USER_MODEL, verbose_name='Resgatado Por'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='data_compra',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_transacao',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='ofertas.oferta'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupom', to='compras.compra'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to='ofertas.oferta'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('resgatado', 'Resgatado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='disponivel', max_length=20),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_cupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='valido_ate',
            field=models.DateTimeField(),
        ),
    ]
