# Generated by Django 5.2.4 on 2025-07-30 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('pedidos_coletivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='pedido_coletivo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupom_coletivo', to='pedidos_coletivos.pedidocoletivo', verbose_name='Pedido Coletivo'),
        ),
        migrations.AddField(
            model_name='cupom',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_cupons', to=settings.AUTH_USER_MODEL, verbose_name='Comprador'),
        ),
    ]
