# Generated by Django 5.2.4 on 2025-07-28 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_cupom_options_remove_compra_data_atualizacao_and_more'),
        ('ofertas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='id_transacao',
        ),
        migrations.AddField(
            model_name='compra',
            name='id_preferencia_mp',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Preferência MP'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_transacao_mp',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Transação MP'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='data_compra',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Compra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='ofertas.oferta', verbose_name='Oferta'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='pendente', max_length=20, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código do Cupom'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupom', to='compras.compra', verbose_name='Compra Relacionada'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='data_geracao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to='ofertas.oferta', verbose_name='Oferta'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('resgatado', 'Resgatado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='disponivel', max_length=20, verbose_name='Status do Cupom'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_cupons', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Dono do Cupom'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='valido_ate',
            field=models.DateTimeField(verbose_name='Válido Até'),
        ),
    ]
