# Generated by Django 5.2.4 on 2025-08-04 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('verb', models.CharField(blank=True, max_length=255, null=True, verbose_name='Verbo/Ação')),
                ('notification_type', models.CharField(blank=True, choices=[('course_update', 'Atualização de Curso'), ('forum_reply', 'Resposta no Fórum'), ('quiz_result', 'Resultado de Quiz'), ('system_alert', 'Alerta do Sistema')], max_length=50, null=True, verbose_name='Tipo de Notificação')),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-timestamp'],
            },
        ),
    ]
