# Generated by Django 5.2.2 on 2025-08-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
