# Generated by Django 5.2.5 on 2025-08-29 14:52

import django.db.models.deletion
import solar.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('solar', '0005_alter_cliente_cnpj_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[solar.models.validar_cnpj]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[solar.models.validar_cnpj]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='solar_usuario_set', related_query_name='solar_usuario', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_crm_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='solar_user_permissions_set', related_query_name='solar_user_permission', to='auth.permission'),
        ),
    ]
