# Generated by Django 5.2.2 on 2025-10-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0008_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='azimute_telhado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Orientação do telhado (0° = Norte).', max_digits=5),
        ),
        migrations.AddField(
            model_name='projeto',
            name='inclinacao_telhado',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Ângulo de inclinação do telhado (em graus).', max_digits=5),
        ),
        migrations.AddField(
            model_name='projeto',
            name='irradiacao_media_diaria',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Média diária de irradiação (kWh/m²/dia).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
