# Generated by Django 5.2.2 on 2025-10-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0009_projeto_azimute_telhado_projeto_inclinacao_telhado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='azimute_telhado',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='inclinacao_telhado',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='longitude',
        ),
    ]
