# Generated by Django 5.2.2 on 2025-10-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0011_projetoexecutado_proposta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjetoExecutado',
        ),
        migrations.DeleteModel(
            name='Proposta',
        ),
    ]
