# Generated by Django 5.2.2 on 2025-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0012_delete_projetoexecutado_delete_proposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoExecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Projeto Residencial em Sorocaba', max_length=200)),
                ('potencia_kwp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('localidade', models.CharField(max_length=100)),
                ('tipo_projeto', models.CharField(choices=[('RES', 'Residencial'), ('COM', 'Comercial'), ('IND', 'Industrial')], max_length=20)),
                ('imagem_capa', models.ImageField(help_text='Imagem de alta resolução do projeto instalado', upload_to='projetos_portfolio/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo no Site')),
            ],
            options={
                'verbose_name': 'Projeto Executado',
                'verbose_name_plural': 'Projetos Executados',
                'ordering': ['-potencia_kwp'],
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('cliente_nome', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('vendedor', models.CharField(max_length=100)),
                ('potencia_kwp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_crm', models.CharField(choices=[('1_ACEITE', '1. Aguardando Aceite'), ('2_PROJETO', '2. Em Elaboração de Projeto'), ('3_HOMOLOG', '3. Em Homologação na Concessionária'), ('4_INSTAL', '4. Instalação Agendada'), ('5_FINALIZADO', '5. Sistema Ativo')], default='1_ACEITE', max_length=20)),
                ('data_validade', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proposta de Cliente',
                'verbose_name_plural': 'Propostas de Clientes',
            },
        ),
    ]
