# Generated by Django 5.2.2 on 2025-10-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0013_projetoexecutado_proposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Breve Descrição')),
                ('imagem', models.ImageField(upload_to='portfolio/%Y/', verbose_name='Foto Principal')),
                ('data_conclusao', models.DateField(verbose_name='Data de Conclusão')),
                ('destaque', models.BooleanField(default=False, help_text='Marque para incluir este projeto nas propostas geradas.', verbose_name='Destacar na Proposta?')),
            ],
            options={
                'ordering': ['-data_conclusao'],
            },
        ),
        migrations.AddField(
            model_name='documentoprojeto',
            name='incluir_na_proposta',
            field=models.BooleanField(default=False, help_text='Marque se este arquivo for uma imagem a ser mostrada na proposta.', verbose_name='Incluir na Proposta PDF?'),
        ),
    ]
