# Generated by Django 5.2.2 on 2025-10-07 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0014_portfolio_documentoprojeto_incluir_na_proposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='area_necessaria_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Área Necessária (m²)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='consumo_medio_kwh',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Consumo Médio Mensal (kWh)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_estrutura',
            field=models.CharField(blank=True, help_text='Ex: Cerâmico, Fibrocimento, Metálico', max_length=100, null=True, verbose_name='Tipo de Estrutura do Telhado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ItemProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Item')),
                ('unidade', models.CharField(default='unid.', max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Unit. (R$)')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_proposta', to='solar.projeto')),
            ],
        ),
    ]
