# Generated by Django 5.2.2 on 2025-10-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0015_projeto_area_necessaria_m2_projeto_consumo_medio_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='projeto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposta', to='solar.projeto'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='numero',
            field=models.CharField(blank=True, help_text='Será gerado automaticamente ao salvar.', max_length=20, unique=True),
        ),
    ]
