# Generated by Django 5.2.2 on 2025-10-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0016_proposta_projeto_alter_proposta_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='potencia_kwp',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
