# Generated by Django 5.2.4 on 2025-07-30 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo de Crédito')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credito_site', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Crédito do Usuário',
                'verbose_name_plural': 'Créditos dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='HistoricoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='Tipo de Transação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('saldo_apos_transacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Após')),
                ('data_transacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Transação')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('credito_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pedidos_coletivos.creditousuario', verbose_name='Crédito do Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Crédito',
                'verbose_name_plural': 'Históricos de Crédito',
                'ordering': ['-data_transacao'],
            },
        ),
        migrations.CreateModel(
            name='PedidoColetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade Comprada')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total do Pedido')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado_mp', 'Aprovado no MP (Aguardando Lote)'), ('recusado', 'Recusado'), ('cancelado_cliente', 'Cancelado pelo Cliente')], default='pendente', max_length=20, verbose_name='Status do Pagamento')),
                ('status_lote', models.CharField(choices=[('aberto', 'Lote Aberto (Aguardando Mínimo)'), ('concretizado', 'Lote Concretizado'), ('falha', 'Lote Falhou (Mínimo Não Atingido)'), ('finalizado_admin', 'Finalizado pelo Admin')], default='aberto', max_length=20, verbose_name='Status do Lote')),
                ('id_transacao_mp', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Transação MP')),
                ('id_preferencia_mp', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Preferência MP')),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pagamento')),
                ('cupom_gerado', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código do Cupom Gerado')),
                ('data_cupom_gerado', models.DateTimeField(blank=True, null=True, verbose_name='Data de Geração do Cupom')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_coletivos', to='ofertas.oferta', verbose_name='Oferta Coletiva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_coletivos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido Coletivo',
                'verbose_name_plural': 'Pedidos Coletivos',
                'ordering': ['-data_pedido'],
            },
        ),
    ]
