# Generated by Django 5.2.4 on 2025-07-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_coletivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocoletivo',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado_mp', 'Aprovado no MP (Aguardando Lote)'), ('recusado', 'Recusado'), ('cancelado_cliente', 'Cancelado pelo Cliente'), ('lote_cancelado_com_credito', 'Lote Cancelado (Crédito Gerado)')], default='pendente', max_length=30, verbose_name='Status do Pagamento'),
        ),
    ]
