# Generated by Django 5.2.2 on 2025-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_projetoexecutado_proposta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjetoExecutado',
        ),
        migrations.DeleteModel(
            name='Proposta',
        ),
        migrations.AddField(
            model_name='produto',
            name='garantia_anos_equipamento',
            field=models.IntegerField(default=1, verbose_name='Garantia Padrão (Anos)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_equipamento',
            field=models.CharField(choices=[('MODULO', 'Módulo Fotovoltaico'), ('INVERSOR', 'Inversor / Microinversor'), ('ESTRUTURA', 'Estrutura de Fixação'), ('ACESSORIO', 'Acessório / Cabo')], default='ACESSORIO', max_length=20),
        ),
    ]
