# Generated by Django 5.2.4 on 2025-10-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='arquivo_edital',
            field=models.FileField(blank=True, help_text='O arquivo PDF original do edital para ser enviado à Audesp.', null=True, upload_to='editais/%Y/%m/', verbose_name='Arquivo PDF do Edital'),
        ),
    ]
