# Generated by Django 5.2.2 on 2025-08-22 19:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import solar.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[solar.models.validar_cnpj])),
                ('telefone', models.CharField(max_length=20, validators=[solar.models.validar_telefone])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('rota', models.CharField(help_text='Exemplo: /clientes/ ou nome da URL Django', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_crm_staff', models.BooleanField(default=False, help_text='Designa se o usuário tem acesso ao CRM (administração, gestão de projetos, etc.)')),
                ('is_customer', models.BooleanField(default=False, help_text='Designa se o usuário é um cliente do e-commerce.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='solar_usuario_set', related_query_name='solar_usuario', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='solar_user_permissions_set', related_query_name='solar_user_permission', to='auth.permission', verbose_name='user permissions')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.departamento')),
                ('permissoes_menu', models.ManyToManyField(blank=True, related_name='usuarios_com_permissao_menu', to='solar.menupermissao')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20, validators=[solar.models.validar_telefone])),
                ('rua', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[solar.models.validar_cnpj])),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[solar.models.validar_cpf])),
                ('possui_whatsapp', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('unidade_medida', models.CharField(max_length=20)),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('preco_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('garantia_ate', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Aguardando aprovação', 'Aguardando aprovação'), ('Cancelado', 'Cancelado'), ('Pendente Orçamento', 'Pendente Orçamento'), ('Em Instalação', 'Em Instalação'), ('Manutenção', 'Manutenção'), ('Homologado', 'Homologado'), ('Proposta Enviada', 'Proposta Enviada')], max_length=50)),
                ('rua', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('potencia_kwp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Potência (kWp)')),
                ('quantidade_modulos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Módulos')),
                ('inversor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo do Inversor')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total (R$)')),
                ('forma_pagamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma de Pagamento')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.cliente')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.fornecedor')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recebimento', 'Recebimento'), ('pagamento', 'Pagamento')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='solar.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('concluida', 'Concluída'), ('em_andamento', 'Em Andamento'), ('pendente', 'Pendente'), ('atrasada', 'Atrasada')], default='pendente', max_length=20)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='solar.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Documento')),
                ('arquivo', models.FileField(upload_to='projetos/%Y/%m/%d/', verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('visivel_cliente', models.BooleanField(default=False, verbose_name='Visível para o cliente?')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='solar.projeto')),
            ],
        ),
    ]
