# Generated by Django 5.2.5 on 2025-08-29 13:41

import solar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_delete_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[solar.models.validar_cnpj]),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[solar.models.validar_cnpj]),
        ),
    ]
