# Generated by Django 5.2.4 on 2025-07-30 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='vendedor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_associado', to='ofertas.vendedor', verbose_name='Vendedor Associado'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
